Define `getindex(::InlineString, range)` to return InlineString (#44)
* Add `getindex` method taking an `AbstractUnitRange`

* Allow `getindex` method to take any `Integer`

* Move const definition outside testset

* Remove unused `ncodeunits` call

* Fix empty range case

* Minor perf cleanup

* fixup! Fix empty range case

* Fix ambiguity error

- Before on Julia v1.6:
  MethodError: getindex(::String255, ::UnitRange{Int64}) is ambiguous. Candidates:
    getindex(s::AbstractString, r::UnitRange{var"#s77"} where var"#s77"<:Integer) in Base at strings/substring.jl:255
    getindex(s::InlineString, r::AbstractUnitRange{var"#s17"} where var"#s17"<:Integer) in InlineStrings at src/InlineStrings.jl:359

* Test on non-UnitRange range type